title: "Secure Software Development"
description: >-
  Assignments and code examples.
source: "./"
incremental: false

# GitHub pages theme
remote_theme: pages-themes/hacker@v0.2.0
plugins:
 - jekyll-remote-theme
theme: jekyll-theme-hacker

# Disable source link in header
github:
  is_project_page: false
